# -*- coding: utf-8 -*-
"""dot_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlcXvciFxk-y6mC5AwQfaGSk9BYl04IA
"""

# import necessary packages
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from pythainlp.tokenize import word_tokenize
from jiwer import process_words, process_characters
import numpy as np
import torchaudio
import torch
import string
import math


class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self

def count_word(text):

    words = text.split()

    return len(words)


def count_chars(text):

    total_chars = 0

    for char in text:

        total_chars += 1

    return total_chars

def clean_text(sentence: str, remove_punctuation: bool = True):
    sentence = sentence.strip()
    # Remove zero-width and non-breaking space.
    sentence = sentence.replace("\u200b", " ")
    sentence = sentence.replace("\xa0", " ")
    # remove redundant punctuations
    sentence = sentence.replace("เเ", "แ")

    # วรรณยุกต์/สระ
    sentence = sentence.replace("ํา", "ำ")
    sentence = sentence.replace("่ำ", "่ำ")
    sentence = sentence.replace("ำ้", "้ำ")
    sentence = sentence.replace("ํ่า", "่ำ")

    # replace special underscore and dash.
    sentence = sentence.replace("▁", "_")
    sentence = sentence.replace("—", "-")
    sentence = sentence.replace("–", "-")
    sentence = sentence.replace("−", "-")

    # replace special characters.
    sentence = sentence.replace("’", "'")
    sentence = sentence.replace("‘", "'")
    sentence = sentence.replace("”", '"')
    sentence = sentence.replace("“", '"')

    if remove_punctuation:
        sentence = "".join(
            [character for character in sentence if character not in string.punctuation]
        )
    return " ".join(sentence.split()).strip()


def tokenize_text(text):
    """
    Perform tokenization to Thai language with pythainlp

    Parameters:
                text: input text
    Return:
                tokenized text
    """

    # remove space
    text = "".join(text.split())

    # clean text
    text = clean_text(text)

    # tokenize the text
    text_tokenize = " ".join(word_tokenize(text))

    # return the tokenized text
    return text_tokenize

def audio_to_text_thonburian_whisper(audio, model, processor, sr=16000, device="cuda"):
    """
    Perform Automatic Speech Recognition

    Parameters:
                audio: input audio, shape = [length]
                model: whisper model
                processor: processor for whisper model
                sr: sampling rate, default = 16k

    Return:
                text: output speech recognition text
    """

    # check the sampling rate to be 16k
    if sr != 16000:
        # print("[INFO] Perform Resampling to 16k.")
        resampler = torchaudio.transforms.Resample(orig_freq=sr, new_freq=16000)
        audio = resampler(audio)
        sr = 16000

    # get input features for the whisper model
    input_features = processor(audio, sampling_rate=sr, return_tensors="pt").input_features

    # generate token ids
    with torch.no_grad():
        # predicted_ids = model.generate(input_features.to(device), forced_decoder_ids=forced_decoder_ids)
        predicted_ids = model.generate(input_features.to(device), language="th", return_timestamps=False)

    # decode token ids to text
    transcription = processor.batch_decode(predicted_ids, skip_special_tokens=True)

    # return the output text
    return transcription[0]

def calculate_objectives(gt_text, asr_text):

    # tokenize texts
    gt_text = tokenize_text(gt_text)
    asr_text = tokenize_text(asr_text)

    # calculate wer, cer, blue_1, blue_2 and blue_4 scores
    measures_words = process_words(reference=gt_text, hypothesis=asr_text)
    total_error_words = measures_words.insertions + measures_words.deletions + measures_words.substitutions
    total_words = count_word(gt_text)

    measures_chars = process_characters(reference=gt_text, hypothesis=asr_text)
    total_error_chars = measures_chars.insertions + measures_chars.deletions + measures_chars.substitutions
    total_chars = count_chars(gt_text)

    # tokenize for BLUE score calculation
    gt_tokens = gt_text.split()
    asr_tokens = asr_text.split()

    # Use smoothing for short sentences (recommended)
    smoothing = SmoothingFunction().method1

    # Compute BLEU
    blue_1 = sentence_bleu([gt_tokens], asr_tokens, weights=(1, 0, 0, 0), smoothing_function=smoothing)
    blue_2 = sentence_bleu([gt_tokens], asr_tokens, weights=(0.5, 0.5, 0, 0), smoothing_function=smoothing)
    blue_4 = sentence_bleu([gt_tokens], asr_tokens, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=smoothing)


    return {
        "total_words": total_words,
        "total_error_words": total_error_words,
        "words_insertions": measures_words.insertions,
        "words_deletions": measures_words.deletions,
        "words_substitutions": measures_words.substitutions,
        "total_chars": total_chars,
        "total_error_chars": total_error_chars,
        "chars_insertions": measures_chars.insertions,
        "chars_deletions": measures_chars.deletions,
        "chars_substitutions": measures_chars.substitutions,
        "blue_1": blue_1,
        "blue_2": blue_2,
        "blue_4": blue_4
        }


def calculate_psnr(clean, denoised, max_val=1.0):
    """Calculate PSNR for a single pair of clean and denoised spectrograms."""
    # Align shapes by truncating to the shorter length
    # min_length = min(clean.shape[0], denoised.shape[0])
    # clean = clean[:min_length]
    # denoised = denoised[:min_length]

    mse = np.mean((clean - denoised) ** 2)
    if mse == 0:
        return float("inf")  # Avoid division by zero, perfect reconstruction
    psnr = 10 * math.log10(max_val**2 / mse)

    return psnr