# -*- coding: utf-8 -*-
"""dot_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlcXvciFxk-y6mC5AwQfaGSk9BYl04IA
"""

# import necessary packages
import torch
import torch.nn.functional as F

def convert_l_sec_to_frames(L_h_sec, Fs=22050, N=1024, H=512):
    """Convert filter length parameter from seconds to frame indices"""
    # Keep behavior consistent with original: return an integer kernel length
    L_h = int(torch.ceil(torch.tensor(L_h_sec, dtype=torch.float32) * float(Fs) / float(H)).item())
    return L_h


def convert_l_hertz_to_bins(L_p_Hz, Fs=22050, N=1024, H=512):
    """Convert filter length parameter from Hertz to frequency bins"""
    L_p = int(torch.ceil(torch.tensor(L_p_Hz, dtype=torch.float32) * float(N) / float(Fs)).item())
    return L_p


def make_integer_odd(n):
    """Convert integer into odd integer"""
    if n % 2 == 0:
        n += 1
    return n


def _median_filter_time(Y, L_h):
    """
    Median filter along time axis for Y with shape [B, F, T]
    Equivalent to signal.medfilt(Y, [1, L_h]) with constant(0) padding.
    """
    pad_t = L_h // 2
    Y_pad = F.pad(Y, (pad_t, pad_t, 0, 0), mode="constant", value=0.0)  # pad time only
    # unfold over time (last dim): -> [B, F, T, L_h]
    Y_win = Y_pad.unfold(dimension=-1, size=L_h, step=1)
    Y_h = Y_win.median(dim=-1).values
    return Y_h


def _median_filter_freq(Y, L_p):
    """
    Median filter along frequency axis for Y with shape [B, F, T]
    Equivalent to signal.medfilt(Y, [L_p, 1]) with constant(0) padding.
    """
    pad_f = L_p // 2
    Y_pad = F.pad(Y, (0, 0, pad_f, pad_f), mode="constant", value=0.0)  # pad freq only
    # unfold over freq (dim=-2): -> [B, F, T, L_p]
    Y_win = Y_pad.unfold(dimension=-2, size=L_p, step=1)
    Y_p = Y_win.median(dim=-1).values
    return Y_p


def hrps(X, Fs, N, H, L_h, L_p, beta=2.0, L_unit='physical'):
    """Harmonic-residual-percussive separation (HRPS) algorithm (PyTorch, batch-capable)

    Args:
        X (torch.Tensor): [T] or [B, T] complex spectrogram
        Fs (scalar): Sampling rate
        N (int): Frame length (n_fft / win_length)
        H (int): Hopsize
        L_h (float|int): Horizontal median filter length (seconds or frames)
        L_p (float|int): Percussive median filter length (Hz or bins)
        beta (float): Separation factor
        L_unit (str): 'physical' or 'indices'
        detail (bool): return dict of internals if True

    Returns:
        x_h, x_p, x_r (torch.Tensor): same shape as x
        details (dict): if detail=True
    """
    assert L_unit in ['physical', 'indices']

    device = X.device
    dtype = X.real.dtype

    # # stft
    # window = torch.hann_window(N, device=device, dtype=dtype)

    # X = torch.stft(x, n_fft=N, hop_length=H, win_length=N,
    #                 window=window, center=True, return_complex=True)  # [B, F, T]

    # power spectrogram
    Y = torch.abs(X) ** 2  # [B, F, T]

    # median filtering
    if L_unit == 'physical':
        L_h = convert_l_sec_to_frames(L_h_sec=L_h, Fs=Fs, N=N, H=H)
        L_p = convert_l_hertz_to_bins(L_p_Hz=L_p, Fs=Fs, N=N, H=H)

    L_h = make_integer_odd(L_h)
    L_p = make_integer_odd(L_p)

    Y_h = _median_filter_time(Y, L_h)  # [B, F, T]
    Y_p = _median_filter_freq(Y, L_p)  # [B, F, T]

    # masking (keep variable names)
    M_h = (Y_h >= float(beta) * Y_p).to(torch.int8)
    M_p = (Y_p >  float(beta) * Y_h).to(torch.int8)

    # take harmonic and percussive as harmonic and the rest is residual
    M_h = M_h + M_p
    M_r = 1 - M_h

    # set the mask to dtype and device
    M_h = M_h.to(dtype=dtype, device=device)
    M_r = M_r.to(dtype=dtype, device=device)

    return M_h, M_r

